Repository myfreecomm/cobrato-api-docs, pull requests merged in 2018-11, with the labels that each got.

#95 Filter for charge configs
  source/includes/_charge_configs.md
Labels: hold

#96 Remove reference for registered_charges and registrable field
  source/includes/_charge_configs.md
  source/includes/_charges.md
Labels: next-release

#101 Add webhook paid payment
  .gitignore
  source/includes/_payloads.md
Labels: review

#102 Specific webhook Payment
  source/includes/_payloads.md
Labels: review, wip

#104 Fix payment webhook payload info
  source/includes/_payloads.md
Labels: review

#103 Improve docs for payments registration status
  source/includes/_payments.md
Labels: review
